<div data-page="schedule" class="page">
	<div class="navbar">
		<div class="navbar-inner">
			<div class="left">
				<a href="#" data-panel="left" class="link open-panel">
					<i class="hamburger hamburger--elastic">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</i>
				</a>
			</div>
			<div class="center">Grade de Aulas & Atividades</div>
		</div>
	</div>
	<div class="page-content"></div>
	<div class="toolbar toolbar-bottom">
        <div class="toolbar-inner">
          <a href="#" class="select-cj button button-fill color-white" data-location="1" data-request="<?php echo $this->url('activity/display/cj')?>">Cidade Jardim</a>
          <a href="#" class="select-vo button button-fill color-white" data-location="2" data-request="<?php echo $this->url('activity/display/vo')?>">Vila Olímpia</a>
       </div>
	</div>
</div>