<div data-page="password-recover" class="page no-navbar">
	<div class="page-content" style="max-width: 400px; margin: auto;">
		<div class="content-block">
			<img class="logo" src="<?php echo $this->basePath('/assets/custom/logo/256x256.png')?>" />
		</div>
		<form name="password-recover" action="<?php echo $this->url('password-recover')?>" method="POST" enctype="multipart/form-data">
			<div class="list-block no-hairlines">
				<ul>
					<li>
						<div class="item-content">
							<div class="item-media">
								<i class="material-icons">fiber_pin</i>
							</div>
							<div class="item-inner">
								<div class="item-input">
									<input type="text" id="numpad" name="code" placeholder="Código Reebok" required/>
								</div>
								<div class="item-text input-error"></div>
							</div>
						</div>
					</li>
					<li>
						<div class="item-content">
							<div class="item-media">
								<i class="material-icons">mail_outline</i>
							</div>
							<div class="item-inner">
								<div class="item-input">
									<input type="email" id="email" name="email" placeholder="E-mail" required />
								</div> 
								<div class="item-text input-error"></div>
							</div>
						</div>
					</li>
				</ul>
			</div>
			<div class="content-block">
				<p><button type="submit" class="button button-big button-block button-fill">Recuperar Senha</button></p>
				<p class="text-center">Lembrou da sua senha? <a href="<?php echo $this->url('login')?>">Efetue seu Login</a>.</p>
			</div>
		</form>
	</div>
</div>