#!/bin/sh
# ---------------------------------------------------------------------------
# Script Path
# ---------------------------------------------------------------------------
SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
# ---------------------------------------------------------------------------
# Image Versions
# ---------------------------------------------------------------------------
DOCKER_IMAGE_VERSION_API="1.0.0.0"
DOCKER_IMAGE_VERSION_GAME="2.6.3.0"
DOCKER_IMAGE_VERSION_LOGIN="2.6.6.0"
DOCKER_IMAGE_VERSION_MARIADB="10.6.12"
# ---------------------------------------------------------------------------
# Manage binfmt dependences
# ---------------------------------------------------------------------------
apt install -y binfmt-support;
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes;
# ---------------------------------------------------------------------------
# Removing all docker images
# ---------------------------------------------------------------------------
docker rm --force $(docker ps --format "{{.ID}}")
docker rmi --force $(docker image list --format "{{.ID}}")
# ---------------------------------------------------------------------------
# Creating docker build enviroment
# ---------------------------------------------------------------------------
docker buildx create --name l2jserver;
docker buildx use l2jserver;
docker buildx inspect --bootstrap;
# ---------------------------------------------------------------------------
# Building L2JServer MariaDB
# ---------------------------------------------------------------------------
cd ${SCRIPT_PATH}/l2jserver-mariadb;
docker build --no-cache --tag edtereza/l2jserver-mariadb:${DOCKER_IMAGE_VERSION_MARIADB} --load .
# ---------------------------------------------------------------------------
# Building L2JServer Login
# ---------------------------------------------------------------------------
cd ${SCRIPT_PATH}/l2jserver-login;
docker build --no-cache --tag edtereza/l2jserver-login:${DOCKER_IMAGE_VERSION_LOGIN} --load .
# ---------------------------------------------------------------------------
# Building L2JServer Game
# ---------------------------------------------------------------------------
cd ${SCRIPT_PATH}/l2jserver-game;
docker build --no-cache --tag edtereza/l2jserver-game:${DOCKER_IMAGE_VERSION_GAME} --load .
# ---------------------------------------------------------------------------
# Back to main folder
# ---------------------------------------------------------------------------
cd ${SCRIPT_PATH}
# ---------------------------------------------------------------------------
# Rebuild docker-compose.yml
# ---------------------------------------------------------------------------
	cat > ${SCRIPT_PATH}/docker-compose.yml << EOF
version: '3.4'
services:
  l2jserver-mariadb:
    container_name: l2jserver-mariadb
    image: edtech/l2jserver-mariadb:${DOCKER_IMAGE_VERSION_MARIADB}
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MARIADB_USERNAME: "l2jserver"
      MARIADB_PASSWORD: "w2nLmpNZfgBWWEVD"
    healthcheck:
      test: healthcheck
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
  l2jserver-login:
    container_name: l2jserver-login
    image: edtech/l2jserver-login:${DOCKER_IMAGE_VERSION_LOGIN}
    restart: always
    links:
      - l2jserver-mariadb
    depends_on:
      - l2jserver-mariadb
    environment:
      JAVA_XMS: "128"
      JAVA_XMX: "256"
      MARIADB_HOST: l2jserver-mariadb
      MARIADB_PORT: "3306"
      MARIADB_DATABASE: "l2jlogin"
      MARIADB_USERNAME: "l2jserver"
      MARIADB_PASSWORD: "w2nLmpNZfgBWWEVD"
      SERVER_UPNP: "True"
      SERVER_BIND: "*"
      SERVER_PORT: "2106"
      SERVER_LISTEN_GAME_SERVER_BIND: "*"
      SERVER_LISTEN_GAME_SERVER_PORT: "9014"
      SERVER_LISTEN_GAME_SERVER_VERSIONS: "6, 14"
      SERVER_LISTEN_GAME_SERVER_AUTO_ACCEPT: "True"
      SERVER_LOGIN_LICENCE: "True"
      SERVER_LOGIN_ALLOWED_IPS: "1"
      SERVER_LOGIN_ATTEMPS_MAX: "5"
      SERVER_LOGIN_ATTEMPS_BAN_SECONDS: "900"
      SERVER_ACCOUNT_AUTO_CREATE: "False"
      SERVER_ACCOUNT_AUTO_CREATE_LEVEL: "0"
      SERVER_ACCOUNT_INACTIVE_ACCESS_LEVEL: "0"
      SERVER_FLOOD_PROTECTION: "True"
      SERVER_FLOOD_PROTECTION_FAST_CONNECTION_TIME: "350"
      SERVER_FLOOD_PROTECTION_FAST_CONNECTION_LIMIT: "15"
      SERVER_FLOOD_PROTECTION_NORMAL_CONNECTION_TIME: "700"
      SYSADMIN_USERNAME: "l2jserver"
      SYSADMIN_PASSWORD: "l2jserver"
    healthcheck:
      test: healthcheck
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    ports:
      - "9014:9014"
      - "2106:2106"
  l2jserver-game:
    container_name: l2jserver-game
    image: edtech/l2jserver-game:${DOCKER_IMAGE_VERSION_GAME}
    restart: always
    links:
      - l2jserver-mariadb
      - l2jserver-login      
    depends_on:
      - l2jserver-mariadb
      - l2jserver-login
    environment:
      JAVA_XMS: "512"
      JAVA_XMX: "8192"
      LOGIN_HOST: l2jserver-login
      LOGIN_PORT: "9014"
      MARIADB_HOST: l2jserver-mariadb
      MARIADB_PORT: "3306"
      MARIADB_DATABASE: "l2jgame"
      MARIADB_USERNAME: "l2jserver"
      MARIADB_PASSWORD: "w2nLmpNZfgBWWEVD"
      SERVER_ID: "1"
      SERVER_UPNP: "True"
      SERVER_BIND: "*"
      SERVER_PORT: "7777"
      SERVER_PLAYER_MAX: "500"
    healthcheck:
      test: healthcheck
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    ports:
      - "7777:7777"
EOF