#!/bin/sh
# ---------------------------------------------------------------------------
# Script Path
# ---------------------------------------------------------------------------
SCRIPT_PATH=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
# ---------------------------------------------------------------------------
# Manage binfmt dependences
# ---------------------------------------------------------------------------
apt install -y binfmt-support;
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes;
# ---------------------------------------------------------------------------
# Creating docker build enviroment
# ---------------------------------------------------------------------------
docker buildx create --name l2jserver;
docker buildx use l2jserver;
docker buildx inspect --bootstrap;
# ---------------------------------------------------------------------------
# Removing all docker images
# ---------------------------------------------------------------------------
docker image rm -f $(docker image ls --format '{{.Repository}}:{{.Tag}}')
# ---------------------------------------------------------------------------
# Building L2JServer MariaDB
# ---------------------------------------------------------------------------
cd ${SCRIPT_PATH}/l2jserver-mariadb;
docker build --tag edtereza/l2jserver-mariadb:10.6.12 --load .
# ---------------------------------------------------------------------------
# Back to main folder
# ---------------------------------------------------------------------------
cd ${SCRIPT_PATH}