version: '3.4'
services:
  l2jserver-mariadb:
    container_name: l2jserver-mariadb
    image: edtereza/l2jserver-mariadb:10.6.12
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MARIADB_USERNAME: "l2jserver"
      MARIADB_PASSWORD: "w2nLmpNZfgBWWEVD"
    healthcheck:
      test: healthcheck
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 5s
    ports:
      - "3306:3306"
    volumes:
      - ./mariadb:/var/lib/mysql
  l2jserver-login:
    container_name: l2jserver-login
    image: edtereza/l2jserver-login:2.6.6.0
    restart: always
    depends_on:
      - l2jserver-mariadb
    environment:
      JAVA_XMS: "128"
      JAVA_XMX: "256"
      MARIADB_HOST: l2jserver-mariadb
      MARIADB_PORT: "3306"
      MARIADB_DATABASE: "l2jlogin"
      MARIADB_USERNAME: "l2jserver"
      MARIADB_PASSWORD: "w2nLmpNZfgBWWEVD"
      SERVER_UPNP: "True"
      SERVER_BIND: "*"
      SERVER_PORT: "2106"
      SERVER_LISTEN_GAME_SERVER_BIND: "*"
      SERVER_LISTEN_GAME_SERVER_PORT: "9014"
      SERVER_LISTEN_GAME_SERVER_VERSIONS: "6, 14"
      SERVER_LISTEN_GAME_SERVER_AUTO_ACCEPT: "True"
      SERVER_LOGIN_LICENCE: "True"
      SERVER_LOGIN_ALLOWED_IPS: "1"
      SERVER_LOGIN_ATTEMPS_MAX: "5"
      SERVER_LOGIN_ATTEMPS_BAN_SECONDS: "900"
      SERVER_ACCOUNT_AUTO_CREATE: "False"
      SERVER_ACCOUNT_AUTO_CREATE_LEVEL: "0"
      SERVER_ACCOUNT_INACTIVE_ACCESS_LEVEL: "0"
      SERVER_FLOOD_PROTECTION: "True"
      SERVER_FLOOD_PROTECTION_FAST_CONNECTION_TIME: "350"
      SERVER_FLOOD_PROTECTION_FAST_CONNECTION_LIMIT: "15"
      SERVER_FLOOD_PROTECTION_NORMAL_CONNECTION_TIME: "700"
      SYSADMIN_USERNAME: "l2jserver"
      SYSADMIN_PASSWORD: "l2jserver"
    healthcheck:
      test: healthcheck
      interval: 5s
      timeout: 2s
      retries: 3
      start_period: 5s
    ports:
      - "9014:9014"
      - "2106:2106"
