<div data-page="terms-usage" class="page">
	<div class="navbar">
		<div class="navbar-inner">
			<div class="left">
				<a href="#" class="link icon-only back">
					<i class="icon icon-back"></i>
				</a>
			</div>
			<div class="center">Termos de Uso</div>
		</div>
	</div>
	<div class="page-content">
		<div class="content-block">
			<div class="alert alert-info">
				<div class="alert-media">
					<i class="fa fa-fw fa-lg fa-info"></i>
				</div>
				<div class="alert-text">Atualizado em 27 de Junho de 2018.</div>
			</div>
		</div>
		<div class="content-block">
			<p>
                O website <b>https://reebokclub.com.br/myreebok/</b> e o aplicativo <b>“My Reebok”</b> das Academias Reebok Sports Club 
                (<b>“Plataforma My Reebok”</b>) são disponibilizados, por mera liberalidade e de forma gratuita, pela MM GLOBAL GYM LTDA.,
                sociedade limitada com sede na Cidade de São Paulo, Estado de São Paulo, à Rua Magalhães de Castro, 12000, loja L 01.4, 
                CEP 05502-001, inscrita no CNPJ/MF sob o n.º 03.602.928/0001-34 (<b>“Reebok</b>”) aos seus alunos, parceiros, convidados e 
				funcionários (<b>“Usuário”</b>) vinculados as unidades Reebok Cidade Jardim e Vila Olímpia.
            </p>
		</div>
		<div class="content-block">
			<p>
                O Usuário poderá fazer uso da Plataforma My Reebok se, de forma voluntária, aceitar estes Termos de Uso e a <a href="<?php echo $this->url('terms/privacy')?>" class="item-link"><b>Política de Privacidade</b></a>, 
                que descrevem as condições aplicáveis ao acesso e uso da destacada plataforma. 
            </p>
		</div>
		<div class="content-block">
			<p>
				<b>
					POR FAVOR, LEIA CUIDADOSAMENTE ESTES TERMOS DE USO ANTES DE UTILIZAR A PLATAFORMA MY REEBOK. NÃO UTILIZE A PLATAFORMA 
					MY REEBOK SE NÃO ESTIVER DE ACORDO COM ESTAS CONDIÇÕES.
				</b>
            </p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">A PLATAFORMA MY REEBOK – FUNCIONALIDADES</div>
		<div class="content-block">
			<p>
				<b>1.</b> A Reebok desenvolveu a Plataforma My Reebok para, em essência, facilitar o acompanhamento, pelo Usuário, das suas atividades 
				físicas, bem como dos eventos e horários de aulas da Reebok. Por meio da Plataforma My Reebok, o Usuário tem acesso:
			</p>
			<p style="padding-left: 20px;">
				<b>*</b> Ao seu código de aluno
			</p>
			<p style="padding-left: 20px;">
				<b>*</b> A informações sobre o plano contratado com a Reebok
			</p>
			<p style="padding-left: 20px;">
				<b>*</b> A informações sobre a validade de exames médicos e ou avaliações físicas realizados para fins da prática de determinados esportes
			</p>
			<p style="padding-left: 20px;">
				<b>*</b> Ao “Vip Friend”, por meio do qual o Usuário poderá indicar um amigo para se matricular na Reebok 		
			</p>
			
			<p style="padding-left: 20px;">
				<b>*</b> Ao “Reebok Informa”, que contém avisos importantes fornecidos pela Reebok, informações sobre eventos que serão realizados, bem 
					como calendário de funcionamento das academias			
			</p>
			<p style="padding-left: 20px;">
				<b>*</b> Ao “Escolha seu Personal”, por meio do qual a Reebok disponibiliza um relatório para que o Usuário preencha com s informações sobre 
					suas medidas e disponibilidades de horário e, assim, a Reebok possa encontrar um personal que se adeque às necessidades indicadas
			</p>
			<p style="padding-left: 20px;">
				<b>*</b> A informações sobre o professor e ferramentas para que o Usuário possa trocá-lo, se for de seu interesse
			</p>
			<p style="padding-left: 20px;">
				<b>*</b> A informações sobre treinos e metas de desenvolvimento do Usuário
			</p>
			<p style="padding-left: 20px;">
				<b>*</b> A informações sobre o IMC (Índice de Massa Corporal) e FCM (Frequência Cardíaca Máxima) do Usuário		
			</p>
			<p style="padding-left: 20px;">
				<b>*</b> A informações sobre o desenvolvimento do Usuário nas diversas modalidades de atividades física, tais como, natação, musculação, crossfit, corrida e ginástica
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">USO DA PLATAFORMA MY REEBOK</div>
		<div class="content-block">
			<p>
				<b>2.</b> Para utilizar a Plataforma MyReebok, o Usuário deverá inserir o seu e-mail, conforme informado no ato de sua matrícula na Reebok 
				e/ou em qualquer outro ato de credenciamento formal com a Reebok (no caso de parceiros, convidados e funcionários), e senha previamente 
				cadastrada (<b>“Dados de Login”</b>). Os Dados de Login são pessoais e intransferíveis, sendo o Usuário o único responsável por qualquer ato (legal ou ilegal) 
				decorrente do uso da Plataforma My Reebok a partir de seu login e senha.
			</p>
			<p style="padding-left: 20px;">
				<b>2.1.</b> A senha inicialmente cadastrada poderá ser modificada a qualquer tempo. Para tanto, basta entrar na Plataforma My Reebok, selecionar o campo 
				<b>“Minhas Informações”</b> e, em seguida, <b>“Alterar Senha”</b>. O Usuário deve criar uma senha forte, com números, letras e outros caracteres.
			</p>
			<p>
				<b>3.</b> O uso da Plataforma My Reebok por crianças e adolescentes menores de 16 (dezesseis) anos deverá ser precedido de consentimento específico de um dos 
				pais ou responsável legal, a quem caberá responsabilidade exclusiva pelos atos praticados pelo aludido Usuário.			
			</p>
			<p style="padding-left: 20px;">
				<b>3.1.</b> Até a obtenção do consentimento referido acima ou tendo sido este revogado, o Usuário em questão não poderá usufruir da Plataforma My Reebok.
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">OBRIGAÇÕES DAS PARTES</div>
		<div class="content-block">
			<p>
				<b>4.</b> O Usuário deve ter cuidado (i) ao utilizar aparelhos celulares e computadores públicos e/ou de terceiros, cuja segurança seja desconhecida ou não seja 
				razoável, (ii) e/ou gravar senhas de forma automática em computadores e dispositivos móveis, (iii) em manter o ambiente do dispositivo utilizado para acesso seguro 
				mediante uso de ferramentas como antivírus e firewall, contribuindo, assim, para prevenção de riscos, pois se o uso da Plataforma My Reebok acarretar qualquer dano 
				a terceiro e/ou violar estes Termos de Uso, a responsabilidade pela reparação será integralmente do Usuário.
			</p>
			<p>
				<b>5.</b> O Usuário concorda em notificar a Reebok imediatamente se suspeitar de qualquer utilização não autorizada de seus Dados de Login. A REEBOK NÃO SERÁ RESPONSÁVEL 
				POR QUAISQUER PERDAS E DANOS RESULTANTES DE ACESSOS NÃO AUTORIZADOS OU USO DE DADOS DE LOGIN, DE UTILIZAÇÃO DE SENHAS VULNERÁVEIS OU, AINDA, DA EXISTÊNCIA DE VÍRUS OU 
				PROGRAMAS MALICIOSOS EM DISPOSITIVOS DE ACESSO.
			</p>
			<p>
				<b>6.</b> O Usuário reconhece e declara que não poderá se envolver em qualquer atividade que prejudique o funcionamento, reduza ou interrompa a Plataforma My Reebok.
			</p>
			<p>
				<b>7.</b> O Usuário não reproduzirá, duplicará, copiará, venderá ou, ainda, comercializará o conteúdo da Plataforma My Reebok para qualquer efeito ou finalidade.
			</p>
			<p>
				<b>8.</b> A Reebok envidará seus melhores esforços para manter as informações e conteúdos disponibilizados na Plataforma My Reebok sempre atualizados, completos e precisos, 
				bem como para corrigir o mais rápido possível eventuais omissões, erros e contradições contidos na Plataforma My Reebok.
			</p>
			<p>
				<b>9.</b> A Reebok envidará seus melhores esforços, também, no que diz respeito à disponibilidade da Plataforma My Reebok, procurando agir de forma a evitar interrupções 
				e erros. Contudo, a Reebok não pode garantir a disponibilização da Plataforma My Reebok em tempo integral, na medida em que esta depende de serviços prestados por terceiros, 
				como empresas de telecomunicações e provedores de acesso à internet. Além disso, a Reebok se reserva o direito de suspender o acesso à Plataforma My Reebok nas hipóteses de 
				caso fortuito, força maior, ataques cibernéticos e, ainda, para atualização e/ou manutenção da Plataforma My Reebok.
			</p>
			<p style="padding-left: 20px;">
				<b>9.1.</b> A Reebok não será, a qualquer título, responsabilizada por danos decorrentes da interrupção de acesso à Plataforma My Reebok, independentemente do motivo e/ou 
				agente que cause a suspensão.
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">PROPRIEDADE INTELECTUAL</div>
		<div class="content-block">
			<p>
				<b>10.</b> A Plataforma My Reebok, assim considerando todo os textos, gráficos, imagens, fotos, ilustrações, marcas comerciais, nomes comerciais, marcas de serviço, logotipos, 
				informações, código-fonte, layouts, nomes de domínio, software, know-how, e outros materiais nela contidos são protegidos por direito de propriedade intelectual (<b>“Direitos
				de Propriedade Intelectual”</b>). Todos os Direitos de Propriedade Intelectual existentes na Plataforma My Reebok são de titularidade ou foram licenciados à Reebok, de modo que 
				apenas a Reebok tem o direito exclusivo de usar, explorar, reproduzir, comercializar ou licenciar a terceiros, de forma gratuita ou onerosa, temporária ou perpétua, proceder às 
				alterações ou melhorias que julgar necessárias, bem como ceder por completo seus Direitos de Propriedade Intelectual, sem que seja devido ao Usuário qualquer remuneração e/ou 
				explicação ou que seja necessária qualquer autorização do Usuário.
			</p>
			<p>
				<b>11.</b> O Usuário, desde já, fica expressamente proibido de: 
			</p>
			<p style="padding-left: 20px;">
				<b>(i)</b> Fazer uso de, divulgar ou explorar quaisquer Direitos de Propriedade Intelectual da Reebok para qualquer finalidade que não a prevista nestes Termos de Uso
			</p>
			<p style="padding-left: 20px;">
				<b>(ii)</b> Contestar qual quer direito, título ou interesse da Reebok em relação aos Direitos de Propriedade Intelectual em quaisquer obras no Brasil ou no exterior 
				relativas à Plataforma My Reebok
			</p>
			<p style="padding-left: 20px;">
				<b>(iii)</b> Registrar, requerer o registo ou auxiliar terceiros a registrar os Direitos de Propriedade Intelectual da Reebok no Brasil ou no exterior relativas à 
				Plataforma My Reebok 
			</p>
			<p style="padding-left: 20px;">
				<b>(iv)</b> Copiar, alterar, adaptar, aprimorar, corrigir, traduzir, atualizar, desenvolver novas versões ou elaborar obras derivadas de quaisquer obras contidas na 
				Plataforma My Reebok
			</p>
			<p style="padding-left: 20px;">
				<b>(v)</b> Copiar, alterar, adaptar, aprimorar, corrigir, traduzir, atualizar, desenvolver novas versões ou elaborar obras derivadas de quaisquer obras contidas na 
				Plataforma My Reebok
			</p>
			<p style="padding-left: 20px;">
				<b>(v)</b> Desmontar, descompilar, fazer engenharia reversa da Plataforma My Reebok ou, por outro meio, de qualquer outra forma, obter, acessar ou tentar obter ou
				acessar código-fonte relacionado à Plataforma My Reebok e/ou qualquer dado ou informação confidencial a ela associado
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">REPONSABILIDADE DAS PARTES</div>
		<div class="content-block">
			<p>
				<b>12.</b> O USUÁRIO SERÁ INTEGRALMENTE RESPONSÁVEL E RESPONDERÁ POR TODO E QUAISQUER DANOS CAUSADOS À REEBOK E/OU A TERCEIROS DEVIDO À MÁ UTILIZAÇÃO DA PLATAFORMA 
				MY REEBOK, SEJA PELO DESCUMPRIMENTO DESTES TERMOS DE USO E/OU VIOLAÇÃO A QUALQUER LEGISLAÇÃO APLICÁVEL
			</p>
			<p>
				<b>13.</b> O USUÁRIO CONCORDA EM ISENTAR, INDENIZAR, DEFENDER E MANTER A REEBOK E SEUS RESPECTIVOS DIRETORES, AGENTES, SÓCIOS, PARCEIROS E FUNCIONÁRIOS, INDENES DE 
				QUALQUER PREJUÍZO, RESPONSABILIDADE, AÇÃO JUDICIAL OU DEMANDA, INCLUINDO HONORÁRIOS ADVOCATÍCIOS E CUSTAS, DECORRENTES DO ACESSO À REDE PLATAFORMA MY REEBOK.
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">POLÍTICA DE PRIVACIDADE</div>
		<div class="content-block">
			<p>
				<b>14.</b> Ao aceitar estes Termos de Uso, o Usuário reconhece que a Reebok pode tratar as suas informações, conforme descrito na <a href="<?php echo $this->url('terms/privacy')?>" class="item-link"><b>Política de Privacidade</b></a>.
			</p>
			<p>
				<b>15.</b> A Reebok, a seu exclusivo critério, pode disponibilizar na Plataforma My Reebok links para websites de terceiros. Essas páginas não foram, necessariamente, 
				revisadas pela Reebok e são mantidas por terceiros sobre os quais a Reebok não exerce qualquer tipo de controle. O uso dessas páginas pelo Usuário é de total responsabilidade deste, 
				que deve se atentar aos Termos de Uso e Política de Privacidade das páginas de Internet visitadas.
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">SUSPENSÃO E CANCELAMENTO DE CONTAS DA PLATAFORMA MY REEBOK</div>
		<div class="content-block">
			<p>
				<b>16.</b> A Reebok terá o direito de suspender ou cancelar imediatamente o acesso do Usuário à Plataforma My Reebok, independentemente de notificação, caso detecte qualquer violação 
				a estes Termos de Uso pelo Usuário. 
			</p>
			<p>
				<b>17.</b> Igualmente, estará cancelado o acesso do Usuário à Plataforma My Reebok caso este desligue-se da Reebok, por qualquer motivo.
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">DISPOSIÇÕES GERAIS</div>
		<div class="content-block">
			<p>
				<b>18.</b> A Reebok poderá, independentemente de qualquer aviso ou notificação, ceder a Plataforma My Reebok a terceiros, a qualquer momento.
			</p>
			<p>
				<b>19.</b> Se qualquer disposição destes Termos de Uso tornar-se inválida ou inexequível, tal disposição será anulada e as demais disposições serão mantidas. 
			</p>
			<p>
				<b>20.</b> A omissão da Reebok com relação a qualquer falha do Usuário em cumprir com estes Termos de Uso não significa renúncia dos direitos da Reebok em agir em relação às 
				falhas subsequentes ou similares.
			</p>
			<p>
				<b>21.</b> As condições especificadas nestes Termos de Uso poderão ser modificadas a qualquer momento. Caso as modificações sejam significativas ou afetem, de forma concreta, 
				os direitos e deveres do Usuário da Plataforma My Reebok, estas lhe serão apresentadas, de forma clara, na próxima vez em que tentar acesso, momento em que lhe será apresentada 
				a nova versão dos Termos de Uso e questionada a sua concordância, antes de continuar utilizando a Plataforma My Reebok.
			</p>
			<p>
				<b>22. A REEBOK PODERÁ INTERROMPER E/OU RESTRINGIR O USO DA PLATAFORMA, POR QUALQUER RAZÃO, SEM QUE QUALQUER DESSAS DECISÕES DA REEBOK OBRIGUE-A A INFORMAR PREVIAMENTE E/OU INDENIZAR O USUÁRIO.</b>
			</p>
			<p>
				<b>23.</b> Estes Termos de Uso serão interpretados e regidos de acordo com as leis da República Federativa do Brasil. Fica eleito o Foro Central da Comarca da Cidade de São Paulo, Estado de São Paulo 
				para dirimir qualquer conflito originado a partir destes Termos de Uso.
			</p>
		</div>
		<div class="content-block">
			<p>
				Em caso de dúvidas a respeito desta Política de Privacidade, contate-nos por meio do SAC, enviando e-mail para <a href="mailto:academia@reebokclub.com.br" target="_blank" class="link external">academia@reebokclub.com.br</a>.
			</p>
		</div>
	</div>
</div>