<div data-page="management-technique-n1-home" class="page">
	<div class="navbar">
		<div class="navbar-inner">
			<div class="left">
				<a href="#" data-panel="left" class="link open-panel">
					<i class="hamburger hamburger--elastic">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</i>
				</a>
			</div>
			<div class="center">Gestão de Operações</div>
		</div>
	</div>
	<div class="page-content">
		<div class="filter">
        	<div class="list-block">
            	<ul>
            		<li>
            			<a href="#" class="item-link smart-select smart-select-n1-filter-location" data-open-in="popup" data-searchbar="false" data-searchbar-placeholder="Localizar" data-searchbar-cancel="Cancelar">
            				<select name="location">
<?php 
    foreach($Filter['Location']['records'] as $Location) {
?>
            					<option value="<?php echo $Location['dbid']?>" <?php echo $Filter['Location']['current'] == $Location['dbid'] ? 'selected="selected"' : ''?>><?php echo $Location['name']?></option>
<?php 
    }
?>
            				</select>
            				<div class="item-content">
            					<div class="item-inner">
            						<div class="item-title">Unidade</div>
            					</div>
            				</div>
            			</a>
            		</li>
            	</ul>
            </div>
            <div class="list-block">
            	<ul>
            		<li>
            			<a href="#" class="item-link smart-select smart-select-n1-filter-date" data-open-in="popup" data-searchbar="true" data-searchbar-placeholder="Localizar" data-searchbar-cancel="Cancelar">
            				<select name="date">
<?php 
    foreach($Filter['Date']['records'] as $Date) {
        $Date['text'] = explode('-', $Date['date']) ;
        $Date['text'] = $Date['text'][1] . '/' . $Date['text'][0];
?>
            					<option value="<?php echo $Date['date']?>" <?php echo $Filter['Date']['current'] == $Date['date'] ? 'selected="selected"' : ''?>><?php echo $Date['text']?></option>
<?php 
    }
?>
            				</select>
            				<div class="item-content">
            					<div class="item-inner">
            						<div class="item-title">Mês de Referência</div>
            					</div>
            				</div>
            			</a>
            		</li>
            	</ul>
            </div>
		</div>
		<div class="data-holder" data-request-url="<?php echo $this->url('management/technique/n1/table')?>" data-request-method="POST"></div>
	</div>
	<div class="popup tablet-fullscreen management-technique-n1-home-popup-nps">
		<div class="toolbar">
			<div class="toolbar-inner">
				<div class="left"></div>
				<div class="right">
					<a href="#" class="link close-popup">
						<i class="material-icons">clear</i>
					</a>
				</div>
			</div>
		</div>
    	<div class="content-block">
			<div id="management-technique-n1-home-popup-nps-graph"  style="height: auto; width: 100%;" data-request-type="nps" data-request-url="<?php echo $this->url('management/technique/n1/graph/nps')?>" data-request-method="POST"></div>
		</div>
	</div>
	<div class="popup tablet-fullscreen management-technique-n1-home-popup-presence">
		<div class="toolbar">
			<div class="toolbar-inner">
				<div class="left"></div>
				<div class="right">
					<a href="#" class="link close-popup">
						<i class="material-icons">clear</i>
					</a>
				</div>
			</div>
		</div>
    	<div class="content-block">
			<div id="management-technique-n1-home-popup-presence-graph"  style="height: auto; width: 100%;" data-request-type="presence" data-request-url="<?php echo $this->url('management/technique/n1/graph/presence')?>" data-request-method="POST"></div>
		</div>
	</div>
</div>