<div data-page="terms" class="page no-navbar">
	<div class="page-content" style="max-width: 500px; margin: auto;">
		<div class="content-block">
			<img class="logo" src="<?php echo $this->basePath('/assets/custom/logo/256x256.png')?>" />
		</div>
		<div class="content-block" style="margin: 0px; padding: 0px;">
			<div class="list-block media-list no-hairlines no-hairlines-between" style="margin: 8px;">
				<ul class="terms-list">
<?php
foreach($Terms as $Term)
{
    $TermURL = null;
    if ($Term['type']['dbid'] == 1) {
        $TermURL = $this->url('terms/usage');
    }
    else if ($Term['type']['dbid'] == 2) {
        $TermURL = $this->url('terms/privacy');
    }
?>
        			<li>
						<div class="card">
							<div class="card-content">
								<div class="card-content-inner">
									<div class="item-content">
										<div class="item-media">
											<a href="<?php echo $TermURL?>">
												<i class="material-icons">important_devices</i>
											</a>
										</div>
										<div class="item-inner">
											<div class="item-title-row">
												<div class="item-title">
													<a href="<?php echo $TermURL?>">
														<?php echo $Term['name']?>
													</a>
												</div>
											</div>
											<div class="item-title-row">
												<div class="item-subtitle">
    												&raquo; Publicado em <?php echo $Term['date']?><br />
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</li>
<?php
}
?>
    			</ul>
			</div>
		</div>
		<div class="content-block" style="margin: 0px; padding: 0px;">
			<div class="list-block media-list no-hairlines no-hairlines-between" style="margin: 8px;">
				<ul class="terms-action">
					<li>
						<div class="item-content">
							<div style="width: 50%; display: inline;">
								<button class="button button-big button-fill button-raised button-decline color-reebok" style="width: 90%;" data-event="DECLINE" data-request="<?php echo $this->url('terms')?>" data-method="POST">NÃO ACEITO</button>
							</div>
							<div style="width: 50%; display: inline;">
								<button class="button button-big button-fill button-raised button-accept color-reebok" style="width: 90%; color: #ffffff" data-event="ACCEPT" data-request="<?php echo $this->url('terms')?>" data-method="POST">ESTOU DE ACORDO</button>
							</div>
            			</div>
					</li>
				</ul>
			</div>
		</div>
	</div>
</div>