<div data-page="terms-privacy" class="page">
	<!-- Begin: Navbar -->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="left">
				<a href="#" class="link icon-only back">
					<i class="icon icon-back"></i>
				</a>
			</div>
			<div class="center">
				Política de Privacidade
			</div>
		</div>
	</div>
	<!-- End: Navbar -->

	<!-- Begin: Page Content -->
  <div class="page-content">

		<div class="content-block">
			<div class="alert alert-info">
				<div class="alert-media">
					<i class="fa fa-fw fa-lg fa-info"></i>
				</div>
				<div class="alert-text">Atualizado em 13 de Maio de 2020.</div>
			</div>
		</div>
		<div class="content-block">
			<p>
                O website <b><a href="https://reebokclub.com.br/myreebok/"  target="_blank" class="link external">“https://reebokclub.com.br/myreebok/”</a></b> e o aplicativo <b>“My  Reebok”</b> das Academias Reebok Sports Club (<b>“Plataforma  My  Reebok”</b>) são disponibilizados, por  mera  liberalidade  e  de  forma  gratuita, pela <b>MM  GLOBAL  GYM  LTDA.</b>, sociedade  limitada  com  sede  na  Cidade  de  São  Paulo,  Estado  de  São  Paulo,  à  Rua Magalhães de Castro, 12000, loja L 01.4, CEP 05502-001, inscrita no CNPJ/MF sob o  n.º  03.602.928/0001-34 (<b>“Reebok”</b>) aos seus alunos, convidados, parceiros e funcionários (<b>“Usuário”</b>), nas unidades Reebok Cidade Jardim e Vila Olímpia.
            </p>
		</div>
		<div class="content-block">
			<p>
				Para assegurar ao Usuário integral respeito à sua privacidade e revelar compromisso em protegê-la, esta Política de Privacidade dispõe sobre o tratamento de dados disponibilizados ou gerados pelo Usuário (coleta, uso e compartilhamento), bem como sua salvaguarda. Igualmente, informa como o Usuário pode entrar em contato em caso de quaisquer dúvidas.
            </p>
		</div>
		<div class="content-block">
			<p>
				O Usuário poderá fazer uso da Plataforma My Reebok se, de forma voluntária, aceitar esta Política de Privacidade e os <a href="<?php echo $this->url('terms/usage')?>" class="item-link"><b>Termos de Uso</b></a>.
            </p>
		</div>
		<div class="content-block">
			<p>
				<b>
					POR FAVOR, LEIA CUIDADOSAMENTE ESTA POLÍTICA ANTES DE UTILIZAR A PLATAFORMA MY REEBOK. NÃO UTILIZE A PLATAFORMA MY REEBOK SE NÃO ESTIVER DE ACORDO COM OS TERMOS DESTE DOCUMENTO.
				</b>
            </p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">INFORMAÇÕES COLETADAS E/OU DISPONIBILIZADAS DO USUÁRIO</div>
		<div class="content-block">
			<p>
				<b>1.</b> Quando o Usuário utiliza a Plataforma My Reebok algumas informações podem ser coletadas automaticamente, incluindo endereço IP, tipo de navegador e sistema operacional. A Reebok também poderá coletar informações usando tecnologias como cookies, que permitem rastrear ou fornecer outros dados sobre a interação do Usuário com a Plataforma My Reebok, bem como o número de identificação do dispositivo de acesso utilizado pelo Usuário (Código ID ou IMEI, por exemplo), data e hora da conexão.
			</p>
			<p>
				<b>2.</b> Para utilizar a Plataforma My Reebok, o Usuário deverá inserir o seu e-mail, conforme informado no ato de sua matrícula na Reebok e/ou em qualquer outro ato de credenciamento formal com a Reebok (no caso de parceiros, convidados e funcionários), e senha previamente cadastrada (<b>“Dados de Login”</b>), dados esses, portanto, que são coletados e podem ser associados ao endereço IP e outros dados mencionados no item 1 acima e, ainda, a outros dados pessoais fornecidos no momento de cadastro do aluno, funcionário na Reebok (<b>“Dados Cadastrais”</b>), tais como: nome, telefone, número de RG e/ou CPF, endereço, peso, altura, entre outros.			
			</p>
			<p style="padding-left: 20px;">
				<b>2.1.</b> O Usuário assume inteira responsabilidade pela guarda, sigilo e boa utilização dos Dados de Login, isentando a Reebok de qualquer responsabilidade nesse sentido.	
			</p>
			<p style="padding-left: 20px;">
				<b>2.2.</b> Os Dados Cadastrais são inseridos na Plataforma My Reebok pela própria Reebok.			
			</p>
			<p>
				<b>3.</b> Considerando ser uma das finalidades do My Reebok facilitar o acompanhamento, pelo Usuário, de suas atividades físicas e níveis de desempenho, na Plataforma My Reebok também são disponibilizadas informações relativas à saúde do Usuário, fruto de exames médicos realizados na Reebok, e níveis de desempenho em diversas modalidades esportivas. Essas informações serão armazenadas e protegidas, igualmente, nos termos desta Política. Os profissionais que terão contato com esses dados estão sujeitos a regras específicas de confidencialidade e outras políticas aplicáveis pela Reebok aos seus parceiros e funcionários/colaboradores.
			</p>
			<p>
				<b>4.</b> Outras informações podem, ainda, ser coletados para a finalidade de atendimento a leis e normativos vinculantes da administração pública.
			</p>
			<p>
				<b>5.</b> Não serão coletados, para as finalidades objeto desta Política, dados pessoais de crianças e adolescentes menores de 16 (dezesseis) anos, a não ser que o uso da Plataforma My Reebok tenha sido autorizado por um dos pais ou responsável legal pelo menor, ou decorra de exigência legal.
			</p>
			<p>
				<b>6.</b> Por meio da Plataforma My Reebok serão ainda coletados nome e e-mail de terceiros indicados pelo Usuário, por meio do “CONVIDE UM AMIGO” para se matricular na Reebok.
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">UTILIZAÇÃO DAS INFORMAÇÕES COLETADAS</div>
		<div class="content-block">
			<p>
				<b>7.</b> As informações coletadas poderão ser utilizadas para as seguintes finalidades: 
			</p>
			<p style="padding-left: 20px;">
				<b>(i) </b> fornecer, manter, proteger e melhorar os serviços prestados pela Reebok
			</p>
			<p style="padding-left: 20px;">
				<b>(ii) </b> permitir acesso a determinadas funcionalidades da Plataforma My Reebok
			</p>
			<p style="padding-left: 20px;">
				<b>(iii) </b> permitir a comunicação da Reebok com o Usuário e envio de informações quanto aos serviços, mudanças e melhorias
			</p>
			<p style="padding-left: 20px;">
				<b>(iv) </b> desenvolver novos serviços/produtos
			</p>
			<p style="padding-left: 20px;">
				<b>(v) </b> proteger os direitos do Usuário, de terceiros e da Reebok
			</p>
			<p style="padding-left: 20px;">
				<b>(vi) </b> proporcionar segurança
			</p>
			<p style="padding-left: 20px;">
				<b>(vii) </b> outras finalidades que justifiquem a sua coleta  	
			</p>
			<p>
				<b>8.</b> A Reebok preserva a privacidade do Usuário e não compartilha as informações coletadas com terceiros, salvo mediante consentimento do próprio Usuário, ordem judicial e/ou obrigação prevista na legislação vigente.
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">GUARDA E SIGILO DAS INFORMAÇÕES DO USUÁRIO</div>
		<div class="content-block">
			<p>
				<b>9.</b> Algumas informações coletadas do Usuário como, por exemplo, endereço de IP, Dados de Login e Dados Cadastrais poderão ser armazenados pelo prazo legal.
			</p>
			<p style="padding-left: 20px;">
				<b>9.1.</b> Algumas informações podem ser processadas e permanecer preservadas por período mais amplo, quando houver solicitação ou obrigação legal, investigações governamentais ou investigações referentes a possíveis violações da lei ou dos <a href="<?php echo $this->url('terms/usage')?>" class="item-link"><b>Termos de Uso</b></a> e desta Política de Privacidade, ou como forma de prevenir ilícitos.
			</p>
			<p style="padding-left: 20px;">
				<b>9.2.</b> Ainda que solicitada a exclusão de informações, estas poderão permanecer armazenadas por justificado período para fins de cumprimento de obrigação eventualmente contratada, utilização na solução de litígios e/ou outras razões permitidas ou advindas de lei.
			</p>
			<p>
				<b>10.</b> É importante para a Reebok salvaguardar os dados do Usuário. Para tanto, utilizam-se sistemas, políticas e procedimentos para manter a precisão das informações coletada, bem como para proteger a confidencialidade e o sigilo de tais dados contra quaisquer perdas, usos indevidos e adulterações.
			</p>
			<p style="padding-left: 20px;">
				<b>10.1.</b> Os empregados, fornecedores e parceiros com os quais a Reebok trabalha e que possuem acesso, sempre restrito e devidamente controlado, as informações do Usuário da Plataforma My Reebok também obedecem esta Política de Privacidade e em caso de violação das cláusulas aqui descritas estarão sujeitos às penalidades prescritas pelas leis civil e penal.
			</p>
			<p>
				<b>11.</b> A informação coletada poderá ser transferida e armazenada em um destino fora do Brasil, sendo certo que a Reebok adotará todos os cuidados razoavelmente necessários para garantir que os dados sejam tratados de modo seguro.
			</p>
			<p>
				<b>12.</b> O USUÁRIO ESTÁ CIENTE DE QUE A TRANSMISSÃO DE INFORMAÇÕES PELA INTERNET NÃO É COMPLETAMENTE SEGURA E, DESSE MODO, A REEBOK NÃO PODE GARANTIR A ABSOLUTA SEGURANÇA DOS DADOS TRANSMITIDOS NA PLATAFORMA MY REEBOK. QUALQUER TRANSMISSÃO É DE EXCLUSIVA RESPONSABILIDADE DO USUÁRIO, QUE, AO CONCORDAR COM A PRESENTE POLÍTICA, RECONHECE E ASSUME EXPRESSAMENTE TAL RESPONSABILIDADE. 
			</p>
			<p>
				<b>13.</b> Quaisquer divulgações legalmente exigidas sobre violações de segurança, confidencialidade ou integridade das informações coletadas, notadamente de dados pessoais armazenados eletronicamente e não criptografados serão, sempre que a lei ou ordem de autoridade competente o exigir, noticiadas adequadamente ao Usuário via e-mail ou disponibilizada nos canais de comunicação da Reebok, na medida em que seja consistente com (i) as necessidades legítimas do cumprimento da lei ou (ii) quaisquer medidas necessárias para determinar o escopo da violação e restaurar a integridade razoável do sistema de dados.
			</p>
			<p>
				<b>14.</b> Eventuais extravasamentos, como “prints” da Plataforma My Reebok, não podem ser controlados e não serão responsabilidade da Reebok. Igualmente, não podem ser controlados os serviços prestados por terceiros alheios à Reebok, e que interfiram no funcionamento da Plataforma My Reebok, tais como, operadoras telefônicas, de modo que eventuais danos por estes causados não serão de responsabilidade da Reebok.
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">ACESSO E CONTROLE QUANTO ÀS INFORMAÇÕES</div>
		<div class="content-block">
			<p>
				<b>15.</b> Caso o Usuário deseje alterar ou atualizar os dados fornecidos à Reebok para fins de acesso e utilização da Plataforma My Reebok, ou, ainda, revogar consentimento 
				para uso de tal ferramenta por menores de idade, poderá fazê-lo por meio do e-mail <a href="mailto:academia@reebokclub.com.br" target="_blank" class="link external">academia@reebokclub.com.br</a>.
			</p>
		</div>
		<div class="content-block-title" style="text-align: center; font-weight: bold;">DISPOSIÇÕES GERAIS</div>
		<div class="content-block">
			<p>
				<b>16.</b> Esta Política abrange apenas a Plataforma My Reebok e não se aplica a serviços que tenham Política de Privacidade separada e/ou sobre os quais a Reebok não exerce qualquer tipo de ingerência.
			</p>
			<p>
				<b>17.</b> As condições especificadas nesta Política de Privacidade poderão ser modificadas a qualquer momento. Caso as modificações sejam significativas ou afetem, de forma concreta, os direitos e deveres aqui dispostos, estas lhe serão apresentadas, de forma clara, na próxima vez em que tentar utilizar a Plataforma My Reebok, momento em que lhe será apresentada a nova versão da Política de Privacidade e questionada a sua concordância, antes de continuar utilizando a Plataforma My Reebok.
			</p>
			<p>
				<b>18.</b> Esta Política de Privacidade não substitui, modifica ou amplia qualquer outra Política de Privacidade que também possa reger o relacionamento do Usuário com a Reebok.
			</p>
			<p>
				<b>19.</b> A presente Política de Privacidade será interpretada e regida de acordo com as leis da República Federativa do Brasil. Fica eleito o Foro Central da Comarca da Cidade de São Paulo, Estado de São Paulo para dirimir qualquer conflito originado a partir desta Política de Privacidade.
			</p>
		</div>
		<div class="content-block">
			<p>
				Em caso de dúvidas a respeito desta Política de Privacidade, contate-nos por meio do SAC, enviando e-mail para <a href="mailto:academia@reebokclub.com.br" target="_blank" class="link external">academia@reebokclub.com.br</a>.
			</p>
		</div>
	</div>
</div>