<div data-page="lgpd-biometric-settings" class="page">
	<div class="navbar">
		<div class="navbar-inner">
			<div class="left">
				<a href="#" class="link icon-only back">
					<i class="icon icon-back"></i>
				</a>
			</div>
			<div class="center">Configurações de Biometria</div>
		</div>
	</div>
	<div class="page-content">
		<div style="max-width: 800px; margin: auto;">
			<div class="content-block-title">CONFIGURAÇÕES DE TRATAMENTO</div>
			<div class="list-block" style="margin: 5px;">
     			<ul>
    				<li>
						<div class="item-content">
							<div class="item-media">
								<i class="material-icons color-reebok">fingerprint</i>
							</div>
							<div class="item-inner">
								<div class="item-title">Permitir Tratamento de Dados Biométricos</div>
								<div class="item-after">
    								<label class="label-switch">
    									<input id="global" name="global" value="1" type="checkbox"<?php echo ($Biometric['fingerprint'] == true || $Biometric['face_recognition'] == true ? " checked" : '')?> data-status="<?php echo ($Biometric['fingerprint'] == true || $Biometric['face_recognition'] == true ? '1' : '0')?>"/>
    									<span class="checkbox"></span>
    								</label>
    							</div>
							</div>
						</div>
						<div class="item-content">
							<div class="item-inner">
								<div class="item-subtitle" style="white-space: normal; text-overflow: inherit; text-align: justify;">Ao permitir que a <b>Reebok Sports Club</b> colete, armazene e trate seus dados biométricos, você poderá utiliza-los para se identificar em nossos serviços, tal como liberar seu acesso a academia, validar seu ticket de estacionamento, entre outros. <br/><br/>Contudo, caso você opte por não permitir que estes dados sejam tratados, sua identificação automatizada ficará exclusivamente voltada a utilização do QRCode de nosso APP.</div>
							</div>
						</div>
    				</li>
    				<li class="settings-biometric-global-off">
						<div class="item-content">
							<div class="item-inner">
								<button id="submit" type="button" class="button button-big button-block button-fill color-reebok" data-request="<?php echo $this->url('totem/lgpd/biometric/settings')?>" data-method="POST">SALVAR PREFERÊNCIAS</button>
							</div>
						</div>
    				</li>
            	</ul>
            </div>
			
			<div class="content-block-title settings-biometric-global-on">CONFIGURAÇÕES DE TIPO DE DADOS</div>
			<div class="list-block settings-biometric-global-on" style="margin: 5px;">
     			<ul>
    				<li>
						<div class="item-content">
							<div class="item-media">
								<i class="material-icons color-reebok">fingerprint</i>
							</div>
							<div class="item-inner">
								<div class="item-title">Permitir Digitais</div>
								<div class="item-after">
    								<label class="label-switch">
    									<input id="fingerprint" name="fingerprint" value="1" type="checkbox"<?php echo ($Biometric['fingerprint'] == true ? " checked" : '')?> data-status="<?php echo ($Biometric['fingerprint'] == true ? '1' : '0')?>"/>
    									<span class="checkbox"></span>
    								</label>
    							</div>
							</div>
						</div>
						<div class="item-content">
							<div class="item-inner">
								<div class="item-subtitle" style="white-space: normal; text-overflow: inherit; text-align: justify;">Ao permitir que a <b>Reebok Sports Club</b> capture e armazene suas digitais, você poderá utiliza-las para se identificar em nossos serviços, tal como liberar seu acesso a academia, validar seu ticket de estacionamento, entre outros. <br/><br/>Contudo, caso você opte por não compartilhar estes dados, você não estará apto a utilizar os leitores de digitais em nossas dependencias.</div>
							</div>
						</div>
    				</li>
    				<li>
						<div class="item-content">
							<div class="item-media">
								<i class="material-icons color-reebok">face</i>
							</div>
							<div class="item-inner">
								<div class="item-title">Permitir Reconhecimento Facial</div>
								<div class="item-after">
    								<label class="label-switch">
    									<input id="face_recognition" name="face_recognition" value="1" type="checkbox"<?php echo ($Biometric['face_recognition'] == true ? " checked" : '')?> data-status="<?php echo ($Biometric['face_recognition'] == true ? '1' : '0')?>"/>
    									<span class="checkbox"></span>
    								</label>
    							</div>
							</div>
						</div>
						<div class="item-content">
							<div class="item-inner">
								<div class="item-subtitle" style="white-space: normal; text-overflow: inherit; text-align: justify;">Ao permitir que a <b>Reebok Sports Club</b> processe sua foto para fins de identificação facial, você poderá utilizar os terminais de reconhecimento facial localizados junto a entrada de nossas unidades. <br/><br/>Contudo, caso você opte por não compartilhar estes dados, sua foto não será processada para os fins de identificação facial, e será removida dos terminais de reconhecimento facial.</div>
							</div>
						</div>
    				</li>
    				<li>
						<div class="item-content">
							<div class="item-inner">
								<button id="submit" type="button" class="button button-big button-block button-fill color-reebok" data-request="<?php echo $this->url('totem/lgpd/biometric/settings')?>" data-method="POST">SALVAR PREFERÊNCIAS</button>
							</div>
						</div>
    				</li>
            	</ul>
            </div>
            <div class="content-block" style="margin: 5px;">
    			<div class="alert alert-info">
    				<div class="alert-text" style="padding: 0px; text-align: justify;">A <b>Reebok Sports Club</b> não compartilha suas informações biométricas com nenhum parceiro, fornecedor ou terceiros, sendo estas de uso exclusivo para sua identificação junto aos nossos serviços, tal como para sua maior segurança e comodidade.</div>
    			</div>
    		</div>
            
		</div>
	</div>
</div>