#!/bin/sh
# ---------------------------------------------------------------------------
# Script Path
# ---------------------------------------------------------------------------
SCRIPT_PATH="/etc/nginx"
# ---------------------------------------------------------------------------
# Config Paths
# ---------------------------------------------------------------------------
PATH_CONFIG_APACHE_HTTP="/etc/apache2/httpd.conf"
PATH_CONFIG_PHP_INI="/etc/php7/php.ini"
# ---------------------------------------------------------------------------
# Shared Files
# ---------------------------------------------------------------------------
PATH_SHARED_WWW="/var/www"
# ---------------------------------------------------------------------------
# Function COPYRIGHT
# ---------------------------------------------------------------------------
container_copyright() {
    echo ''
}
# ---------------------------------------------------------------------------
# Function TRAP
# ---------------------------------------------------------------------------
container_trap() {
    httpd -k stop
}
trap container_trap SIGINT SIGTERM
# ---------------------------------------------------------------------------
# Function LOG
# ---------------------------------------------------------------------------
container_log() {
	LOG_TEXT=$1
    LOG_INFO=$2
	LOG_MSEC=$(date "+%N")
	LOG_DATE=$(date "+%Y-%m-%d")
    LOG_TIME=$(date "+%H:%M:%S")
	# STDOUT
	echo "[${LOG_DATE} ${LOG_TIME}.${LOG_MSEC:0:5}] [${LOG_INFO}] ${LOG_TEXT}"	
}

# ---------------------------------------------------------------------------
# Function PARAMS
# ---------------------------------------------------------------------------
container_params() {
    #
    #
    container_log "Database Params" "INFO"
    #
    MARIADB_HOST=${MARIADB_HOST:-"127.0.0.1"}
    MARIADB_PORT=${MARIADB_PORT:-"3306"}
    let MARIADB_PORT=$(echo $MARIADB_PORT | sed 's/[^0-9]*//g')
    MARIADB_DATABASE=${MARIADB_DATABASE:-"l2jlogin"}
    MARIADB_USERNAME=${MARIADB_USERNAME:-"l2jlogin"}
    MARIADB_PASSWORD=${MARIADB_PASSWORD:-"l2jlogin"}
    MARIADB_IDLE_TIME=${MARIADB_IDLE_TIME:-"30"}
    let MARIADB_IDLE_TIME=$(echo $MARIADB_IDLE_TIME | sed 's/[^0-9]*//g')
    let MARIADB_IDLE_TIME=0
    MARIADB_CONNECTIONS=${MARIADB_CONNECTIONS:-"16"}
    let MARIADB_CONNECTIONS=$(echo $MARIADB_CONNECTIONS | sed 's/[^0-9]*//g')
    #
    if [[ "$MARIADB_HOST" == '' ]];
        then
            container_log "- MARIADB_HOST cannot be empty" "ERROR"
            container_log "- - A valid hostname or ip address has required." "ERROR"
            return 0
		fi
    if [[ ! $MARIADB_PORT =~ ^[0-9]{1,10}$ ]];
        then
            container_log "- MARIADB_PORT has invalid" "ERROR"
            container_log "- - A valid connection port has required." "ERROR"
            return 0
		fi
    if [[ "$MARIADB_DATABASE" == '' ]];
        then
            container_log "- MARIADB_DATABASE cannot be empty" "ERROR"
            container_log "- - A valid database name has required." "ERROR"
            return 0
		fi
    if [[ "$MARIADB_USERNAME" == '' ]];
        then
            container_log "- MARIADB_USERNAME cannot be empty" "ERROR"
            container_log "- - A valid username has required." "ERROR"
            return 0
		fi
    if [[ "$MARIADB_PASSWORD" == '' ]];
        then
            container_log "- MARIADB_PASSWORD cannot be empty" "ERROR"
            container_log "- - A valid password has required." "ERROR"
            return 0
		fi
    if [[ ! $MARIADB_IDLE_TIME =~ ^[0-9]{1,10}$ ]];
        then
            container_log "- MARIADB_IDLE_TIME has invalid" "ERROR"
            container_log "- - A valid iddle time for connections has required." "ERROR"
            return 0
		fi
    if [[ ! $MARIADB_CONNECTIONS =~ ^[0-9]{1,10}$ ]];
        then
            container_log "- MARIADB_CONNECTIONS has invalid" "ERROR"
            container_log "- - A valid number of connections has required." "ERROR"
            return 0
		fi
    #
    container_log " - Database Settings" "INFO"
	container_log " - - HOST........: ${MARIADB_HOST}" "INFO"
	container_log " - - PORT........: ${MARIADB_PORT}" "INFO"
	container_log " - - DATABASE....: ${MARIADB_DATABASE}" "INFO"
	container_log " - - USERNAME....: ${MARIADB_USERNAME}" "INFO"
	container_log " - - PASSWORD....: ${MARIADB_PASSWORD}" "INFO"
	container_log " - - IDLE TIME...: ${MARIADB_IDLE_TIME}" "INFO"
	container_log " - - CONNECTIONS.: ${MARIADB_CONNECTIONS}" "INFO"
	export MARIADB_HOST=$MARIADB_HOST
	export MARIADB_PORT=$MARIADB_PORT
    export MARIADB_DATABASE=$MARIADB_DATABASE
    export MARIADB_USERNAME=$MARIADB_USERNAME
    export MARIADB_PASSWORD=$MARIADB_PASSWORD
    export MARIADB_IDLE_TIME=$MARIADB_IDLE_TIME
    export MARIADB_CONNECTIONS=$MARIADB_CONNECTIONS
        #
    container_log "Apache Params" "INFO"
    APACHE_SERVER_ADMIN=${APACHE_SERVER_ADMIN:-"admin@localhost"}
    #
    container_log "PHP Params" "INFO"
	#
    PHP_EXPOSE=${PHP_EXPOSE:-"On"}
    PHP_CHARSET=${PHP_CHARSET:-"UTF8"}
    PHP_TIMEZONE=${PHP_TIMEZONE:-"America/Sao_Paulo"}
    PHP_MEMORY_LIMIT=${PHP_MEMORY_LIMIT:-"128M"}
    PHP_MAX_EXECUTION_TIME=${PHP_MAX_EXECUTION_TIME:-"300"}
    PHP_MAX_INPUT_TIME=${PHP_MAX_INPUT_TIME:-"600"}
    PHP_MAX_INPUT_VARS=${PHP_MAX_INPUT_VARS:-"512"}
    PHP_POST_MAX_SIZE=${PHP_POST_MAX_SIZE:-"512M"}
    PHP_FILE_UPLOADS=${PHP_FILE_UPLOADS:-"On"}
    PHP_UPLOAD_MAX_FILESIZE=${PHP_UPLOAD_MAX_FILESIZE:-"512M"}
    PHP_MAX_FILE_UPLOADS=${PHP_MAX_FILE_UPLOADS:-"20"}
    PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-"E_COMPILE_ERROR\|E_RECOVERABLE_ERROR\|E_ERROR\|E_CORE_ERROR"}
    PHP_DISPLAY_ERRORS=${PHP_DISPLAY_ERRORS:-"On"}
    PHP_DISPLAY_STARTUP_ERRORS=${PHP_DISPLAY_STARTUP_ERRORS:-"On"}
    PHP_LOG_ERRORS=${PHP_LOG_ERRORS:-"On"}
    PHP_LOG_ERRORS_MAX_LEN=${PHP_LOG_ERRORS_MAX_LEN:-"4096"}
    PHP_HTML_ERRORS=${PHP_HTML_ERRORS:-"On"}
    container_log "- Global" "INFO"
	container_log "- - expose_php.............: ${PHP_EXPOSE}" "INFO"
	container_log "- - default_charset........: ${PHP_CHARSET}" "INFO"
	container_log "- - date.timezone..........: ${PHP_TIMEZONE}" "INFO"
    container_log "- Error Logging" "INFO"
	container_log "- - log_errors.............: ${PHP_LOG_ERRORS}" "INFO"
	container_log "- - html_errors............: ${PHP_LOG_ERRORS_MAX_LEN}" "INFO"
	container_log "- - display_errors.........: ${PHP_DISPLAY_ERRORS}" "INFO"
	container_log "- - display_startup_errors.: ${PHP_DISPLAY_STARTUP_ERRORS}" "INFO"
	container_log "- - error_reporting........: ${PHP_ERROR_REPORTING}" "INFO"
    container_log "- Script Execution" "INFO"
	container_log "- - memory_limit...........: ${PHP_MEMORY_LIMIT}" "INFO"
	container_log "- - max_execution_time.....: ${PHP_MAX_EXECUTION_TIME}" "INFO"
	container_log "- - max_input_time.........: ${PHP_MAX_INPUT_TIME}" "INFO"
	container_log "- - max_input_vars.........: ${PHP_MAX_INPUT_VARS}" "INFO"
	container_log "- - post_max_size..........: ${PHP_POST_MAX_SIZE}" "INFO"
	container_log "- - file_uploads...........: ${PHP_FILE_UPLOADS}" "INFO"
	container_log "- - upload_max_filesize....: ${PHP_UPLOAD_MAX_FILESIZE}" "INFO"
	container_log "- - max_file_uploads.......: ${PHP_MAX_FILE_UPLOADS}" "INFO"
    export PHP_EXPOSE=$PHP_EXPOSE
    export PHP_CHARSET=$PHP_CHARSET
    export PHP_TIMEZONE=$PHP_TIMEZONE
    export PHP_MEMORY_LIMIT=$PHP_MEMORY_LIMIT
    export PHP_MAX_EXECUTION_TIME=$PHP_MAX_EXECUTION_TIME
    export PHP_MAX_INPUT_TIME=$PHP_MAX_INPUT_TIME
    export PHP_MAX_INPUT_VARS=$PHP_MAX_INPUT_VARS
    export PHP_POST_MAX_SIZE=$PHP_POST_MAX_SIZE
    export PHP_FILE_UPLOADS=$PHP_FILE_UPLOADS
    export PHP_UPLOAD_MAX_FILESIZE=$PHP_UPLOAD_MAX_FILESIZE
    export PHP_MAX_FILE_UPLOADS=$PHP_MAX_FILE_UPLOADS
    export PHP_ERROR_REPORTING=$PHP_ERROR_REPORTING
    export PHP_DISPLAY_ERRORS=$PHP_DISPLAY_ERRORS
    export PHP_DISPLAY_STARTUP_ERRORS=$PHP_DISPLAY_STARTUP_ERRORS
    export PHP_LOG_ERRORS=$PHP_LOG_ERRORS
    export PHP_LOG_ERRORS_MAX_LEN=$PHP_LOG_ERRORS_MAX_LEN
    export PHP_HTML_ERRORS=$PHP_HTML_ERRORS
    #
	return 1
}
# ---------------------------------------------------------------------------
# Function CONFIG
# ---------------------------------------------------------------------------
container_config() {
    #
    container_log "Setup Config" "INFO"
    #
    container_log "- $PATH_CONFIG_PHP_INI" "INFO"
    if [[ ! -f "$PATH_CONFIG_PHP_INI.bak" ]];
        then
            cp $PATH_CONFIG_PHP_INI "$PATH_CONFIG_PHP_INI.bak"
        fi
    cat > $PATH_CONFIG_PHP_INI << EOF
[PHP]
engine = On
short_open_tag = Off
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
unserialize_callback_func =
serialize_precision = -1
disable_functions =
disable_classes =
zend.enable_gc = On
zend.exception_ignore_args = On
zend.exception_string_param_max_len = 0
expose_php = ${PHP_EXPOSE}
max_execution_time = ${PHP_MAX_EXECUTION_TIME}
max_input_time = ${PHP_MAX_INPUT_TIME}
max_input_vars = ${PHP_MAX_INPUT_VARS}
memory_limit = ${PHP_MEMORY_LIMIT}M
error_reporting = ${PHP_ERROR_REPORTING}
display_errors = ${PHP_DISPLAY_ERRORS}
display_startup_errors = ${PHP_DISPLAY_STARTUP_ERRORS}
log_errors = ${PHP_LOG_ERRORS}
log_errors_max_len = ${PHP_LOG_ERRORS_MAX_LEN}
ignore_repeated_errors = Off
ignore_repeated_source = Off
report_memleaks = On
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off
auto_globals_jit = On
post_max_size = ${PHP_POST_MAX_SIZE}M
auto_prepend_file =
auto_append_file =
default_mimetype = "text/html"
default_charset = "${PHP_CHARSET}"
include_path = ".:/usr/share/php8"
doc_root =
user_dir =
enable_dl = Off
file_uploads = ${PHP_FILE_UPLOADS}
upload_max_filesize = ${PHP_UPLOAD_MAX_FILESIZE}M
max_file_uploads = ${PHP_MAX_FILE_UPLOADS}
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 5
[CLI Server]
cli_server.color = On
[Date]
date.timezone = ${PHP_TIMEZONE}
date.default_latitude = 31.7667
date.default_longitude = 35.2333
date.sunrise_zenith = 90.833333
date.sunset_zenith = 90.833333
[Session]
session.save_handler = files
session.use_strict_mode = 0
session.use_cookies = 1
session.use_only_cookies = 1
session.name = SID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.cookie_httponly =
session.cookie_samesite =
session.serialize_handler = php
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.referer_check =
session.cache_limiter = nocache
session.cache_expire = 720
session.use_trans_sid = 0
session.sid_length = 256
session.trans_sid_tags = "a=href,area=href,frame=src,form="
session.sid_bits_per_character = 5
EOF
    #
    container_log "- $PATH_CONFIG_APACHE_HTTP" "INFO"
    if [[ ! -f "$PATH_CONFIG_APACHE_HTTP.bak" ]];
        then
            cp $PATH_CONFIG_APACHE_HTTP "$PATH_CONFIG_APACHE_HTTP.bak"
        fi
    cat > $PATH_CONFIG_APACHE_HTTP << EOF
ServerTokens Full
ServerRoot /var/www
Listen 80
#LoadModule mpm_event_module modules/mod_mpm_event.so
#LoadModule mpm_prefork_module modules/mod_mpm_prefork.so
#LoadModule mpm_worker_module modules/mod_mpm_worker.so
LoadModule authn_file_module modules/mod_authn_file.so
#LoadModule authn_dbm_module modules/mod_authn_dbm.so
#LoadModule authn_anon_module modules/mod_authn_anon.so
#LoadModule authn_dbd_module modules/mod_authn_dbd.so
#LoadModule authn_socache_module modules/mod_authn_socache.so
LoadModule authn_core_module modules/mod_authn_core.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
LoadModule authz_user_module modules/mod_authz_user.so
#LoadModule authz_dbm_module modules/mod_authz_dbm.so
#LoadModule authz_owner_module modules/mod_authz_owner.so
#LoadModule authz_dbd_module modules/mod_authz_dbd.so
LoadModule authz_core_module modules/mod_authz_core.so
LoadModule access_compat_module modules/mod_access_compat.so
LoadModule auth_basic_module modules/mod_auth_basic.so
#LoadModule auth_form_module modules/mod_auth_form.so
#LoadModule auth_digest_module modules/mod_auth_digest.so
#LoadModule allowmethods_module modules/mod_allowmethods.so
#LoadModule file_cache_module modules/mod_file_cache.so
#LoadModule cache_module modules/mod_cache.so
#LoadModule cache_disk_module modules/mod_cache_disk.so
#LoadModule cache_socache_module modules/mod_cache_socache.so
#LoadModule socache_shmcb_module modules/mod_socache_shmcb.so
#LoadModule socache_dbm_module modules/mod_socache_dbm.so
#LoadModule socache_memcache_module modules/mod_socache_memcache.so
#LoadModule socache_redis_module modules/mod_socache_redis.so
#LoadModule watchdog_module modules/mod_watchdog.so
#LoadModule macro_module modules/mod_macro.so
#LoadModule dbd_module modules/mod_dbd.so
#LoadModule dumpio_module modules/mod_dumpio.so
#LoadModule echo_module modules/mod_echo.so
#LoadModule buffer_module modules/mod_buffer.so
#LoadModule data_module modules/mod_data.so
#LoadModule ratelimit_module modules/mod_ratelimit.so
LoadModule reqtimeout_module modules/mod_reqtimeout.so
#LoadModule ext_filter_module modules/mod_ext_filter.so
#LoadModule request_module modules/mod_request.so
#LoadModule include_module modules/mod_include.so
LoadModule filter_module modules/mod_filter.so
#LoadModule reflector_module modules/mod_reflector.so
#LoadModule substitute_module modules/mod_substitute.so
#LoadModule sed_module modules/mod_sed.so
#LoadModule charset_lite_module modules/mod_charset_lite.so
LoadModule deflate_module modules/mod_deflate.so
LoadModule mime_module modules/mod_mime.so
LoadModule log_config_module modules/mod_log_config.so
#LoadModule log_debug_module modules/mod_log_debug.so
#LoadModule log_forensic_module modules/mod_log_forensic.so
#LoadModule logio_module modules/mod_logio.so
LoadModule env_module modules/mod_env.so
#LoadModule mime_magic_module modules/mod_mime_magic.so
LoadModule expires_module modules/mod_expires.so
LoadModule headers_module modules/mod_headers.so
#LoadModule usertrack_module modules/mod_usertrack.so
#LoadModule unique_id_module modules/mod_unique_id.so
LoadModule setenvif_module modules/mod_setenvif.so
LoadModule version_module modules/mod_version.so
#LoadModule remoteip_module modules/mod_remoteip.so
#LoadModule session_module modules/mod_session.so
#LoadModule session_cookie_module modules/mod_session_cookie.so
#LoadModule session_crypto_module modules/mod_session_crypto.so
#LoadModule session_dbd_module modules/mod_session_dbd.so
#LoadModule slotmem_shm_module modules/mod_slotmem_shm.so
#LoadModule slotmem_plain_module modules/mod_slotmem_plain.so
#LoadModule dialup_module modules/mod_dialup.so
#LoadModule http2_module modules/mod_http2.so
LoadModule unixd_module modules/mod_unixd.so
#LoadModule heartbeat_module modules/mod_heartbeat.so
#LoadModule heartmonitor_module modules/mod_heartmonitor.so
LoadModule status_module modules/mod_status.so
LoadModule autoindex_module modules/mod_autoindex.so
#LoadModule asis_module modules/mod_asis.so
#LoadModule info_module modules/mod_info.so
#LoadModule suexec_module modules/mod_suexec.so
#LoadModule vhost_alias_module modules/mod_vhost_alias.so
#LoadModule negotiation_module modules/mod_negotiation.so
LoadModule dir_module modules/mod_dir.so
#LoadModule actions_module modules/mod_actions.so
#LoadModule speling_module modules/mod_speling.so
#LoadModule userdir_module modules/mod_userdir.so
LoadModule alias_module modules/mod_alias.so
LoadModule rewrite_module modules/mod_rewrite.so
LoadModule negotiation_module modules/mod_negotiation.so
<IfModule !mpm_prefork_module>
        #LoadModule cgid_module modules/mod_cgid.so
</IfModule>
<IfModule mpm_prefork_module>
        #LoadModule cgi_module modules/mod_cgi.so
</IfModule>
<IfModule unixd_module>
    User apache
    Group apache
</IfModule>
ServerAdmin $APACHE_SERVER_ADMIN
ServerSignature Off
ServerName localhost:80
<Directory />
    AllowOverride All
    Require all denied
</Directory>
DocumentRoot "/var/www/public"
<Directory "/var/www/public">
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>
<IfModule dir_module>
    DirectoryIndex index.html index.php
</IfModule>
<Files ".ht*">
    Require all denied
</Files>
ErrorLog logs/error.log
LogLevel warn
<IfModule log_config_module>
    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%h %l %u %t \"%r\" %>s %b" common
    <IfModule logio_module>
      LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>
    CustomLog logs/access.log combined
</IfModule>
<IfModule alias_module>
    ScriptAlias /cgi-bin/ "/var/www/cgi-bin/"
</IfModule>
<IfModule cgid_module>
    #Scriptsock cgisock
</IfModule>
<Directory "/var/www/cgi-bin">
    AllowOverride All
    Options None
    Require all granted
</Directory>
<IfModule headers_module>
    RequestHeader unset Proxy early
</IfModule>
<IfModule mime_module>
    TypesConfig /etc/apache2/mime.types
    #AddType application/x-gzip .tgz
    #AddEncoding x-compress .Z
    #AddEncoding x-gzip .gz .tgz
    AddType application/x-compress .Z
    AddType application/x-gzip .gz .tgz
    #AddHandler cgi-script .cgi
    #AddHandler type-map var
    #AddType text/html .shtml
    #AddOutputFilter INCLUDES .shtml
</IfModule>
<IfModule mime_magic_module>
    MIMEMagicFile /etc/apache2/magic
</IfModule>
#ErrorDocument 500 "The server made a boo boo."
#ErrorDocument 404 /missing.html
#ErrorDocument 404 "/cgi-bin/missing_handler.pl"
#ErrorDocument 402 http://www.example.com/subscription_info.html
#MaxRanges unlimited
#EnableMMAP off
#EnableSendfile on
IncludeOptional /etc/apache2/conf.d/*.conf
EOF
    #
	return 1
}
# ---------------------------------------------------------------------------
# Function DATABASE
# ---------------------------------------------------------------------------
container_database() {
    #
    container_log "Database Management" "INFO"
    #
    container_log "- Checking connectivity" "INFO"
    CHECK_MARIADB_CONNECTION=$(mysql -h ${MARIADB_HOST} -u${MARIADB_USERNAME} -p${MARIADB_PASSWORD} -e "SHOW DATABASES" 2>&1)
    if [[ $? -eq 1 ]];
        then
            container_log "- - Can't connect on database" "ERROR"
            return 0
        else
            container_log "- - Successfully connected" "INFO"
		fi
    #
	return 1 
}
# ---------------------------------------------------------------------------
# Main Events
# ---------------------------------------------------------------------------
#
container_copyright
#
container_params
CONTAINER_PARAMS_CHECK=$?
if [[ $CONTAINER_PARAMS_CHECK -eq 0 ]];
	then
        exit 1
	fi
#
container_config
CONTAINER_CONFIG_CHECK=$?
if [[ $CONTAINER_CONFIG_CHECK -eq 0 ]];
	then
		exit 1
	fi
#
container_database
CONTAINER_DATABASE_CHECK=$?
if [[ $CONTAINER_DATABASE_CHECK -eq 0 ]];
	then
		exit 1
	fi
#
container_log "##########################################################################################" "INFO"
#
chown apache:apache $PATH_SHARED_WWW -R
httpd -e info -D FOREGROUND
#
exit 0