<div data-page="activity" class="page" data-request="<?php echo $this->url('activity/display')?>" data-filter="<?php echo $this->url('activity/filter')?>">
	<div class="navbar">
		<div class="navbar-inner">
			<div class="left">
				<a href="#" data-panel="left" class="link open-panel">
					<i class="hamburger hamburger--elastic">
						<span class="hamburger-box">
							<span class="hamburger-inner"></span>
						</span>
					</i>
				</a>
			</div>
			<div class="center">Grade de Aulas</div>
			<!-- 
			<div class="right">
				<a href="#" data-popup=".popup-filter" class="link open-popup">
					<i class="fas fa-filter"></i>
				</a>
			</div>
            -->
		</div>
	</div>
	<div class="page-content pull-to-refresh-content">
		<div class="pull-to-refresh-layer">
            <div class="preloader"></div>
			<div class="pull-to-refresh-arrow"></div>
		</div>
		<div class="header">
    		<div class="filter">
    			<div class="filter-daytime">
    				<div class="button" data-daytime="1">
	    				<div class="icon">
    						<i class="fas fa-cloud-sun"></i>
	    				</div>
    					MANHÃ
    				</div>
    			</div>
    			<div class="filter-daytime">
    				<div class="button" data-daytime="2">
        				<div class="icon">
        					<i class="fas fa-sun"></i>
        				</div>
        				TARDE
        			</div>
    			</div>
    			<div class="filter-daytime">
    				<div class="button" data-daytime="3">
        				<div class="icon">
        					<i class="fas fa-cloud-moon"></i>
        				</div>
        				NOITE
        			</div>
    			</div>
    		</div>
		</div>
		<div class="result"></div>
	</div>
	<div class="toolbar toolbar-bottom">
        <div class="toolbar-inner">
          <a href="#" class="button button-fill color-white" data-location="1">Cidade Jardim</a>
          <a href="#" class="button button-fill color-white" data-location="2">Vila Olímpia</a>
       </div>
	</div>
	<div class="popup tablet-fullscreen popup-filter">
    	<div class="toolbar">
			<div class="toolbar-inner">
				<div class="left"></div>
				<div class="right">
					<a href="#" class="link close-popup">
						<i class="material-icons">clear</i>
					</a>
				</div>
			</div>
		</div>
		<div class="content-block">
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
		</div>
	</div>
</div>