<html>
	<head></head>
	<body bgcolor="#FAFAFA">
		<p align="left">
			<font face="Verdana, Arial, Helvetica, sans-serif" size="2">Estamos enviando sua senha gerada no cadastramento MyReebok.
    			<br>&nbsp;<br>Aluno: #<?php echo $Pessoa['PessoaID']?> <?php echo $Pessoa['PessoaNome']?> 
    			<br>&nbsp;<br>Senha: <b><?php echo $Senha?></b>
    			<br>&nbsp;<br>&nbsp;
    			<br>Atenciosamente<br>Reebok Sports Club
			</font>
			<br>&nbsp;<br>&nbsp;<br>
			<font face="Verdana, Arial, Helvetica, sans-serif" color="#707070" size="1">
				***** Este é um e-mail automatizado, favor não respondê-lo. Para outras informações fale com um de nossos promotores *****
			</font>
		</p>
	</body>
</html>